import { SuspiciousCommit } from './correlateRecentCommits';

export interface FixPatchInput {
  detectedErrors: string[];
  detectedFiles: string[];
  suspiciousCommits: SuspiciousCommit[];
}

export interface FixPatchResult {
  branchName: string;
  commitMessage: string;
  pullRequestTitle: string;
  pullRequestBody: string;
}

/**
 * Generates mock patch metadata for auto-fix pull requests.
 * Currently generates metadata using TypeScript string formatting.
 * Designed to be replaced with actual patch generation logic in the future.
 * 
 * @param input - Detected errors, files, and suspicious commits
 * @returns Patch metadata including branch name, commit message, PR title and body
 */
export function generateFixPatch(input: FixPatchInput): FixPatchResult {
  const { detectedErrors, detectedFiles, suspiciousCommits } = input;

  // Generate branch name with timestamp
  const timestamp = Date.now();
  const branchName = `fix/regression-${timestamp}`;

  // Generate commit message
  const commitMessage = 'fix: resolve detected regression issue';

  // Generate pull request title
  const pullRequestTitle = 'Auto-fix: Resolve Detected Regression';

  // Generate pull request body
  const pullRequestBody = generatePullRequestBody(
    detectedErrors,
    detectedFiles,
    suspiciousCommits
  );

  return {
    branchName,
    commitMessage,
    pullRequestTitle,
    pullRequestBody,
  };
}

/**
 * Generates the pull request body with detected information.
 */
function generatePullRequestBody(
  errors: string[],
  files: string[],
  commits: SuspiciousCommit[]
): string {
  const sections: string[] = [];

  // Header
  sections.push('## Auto-Generated Fix');
  sections.push('');
  sections.push('This pull request was automatically generated to address a detected regression.');
  sections.push('');

  // Detected Files section
  sections.push('### Detected Files');
  if (files.length > 0) {
    sections.push('');
    sections.push('The following files were identified in the failure logs:');
    sections.push('');
    files.forEach(file => {
      sections.push(`- \`${file}\``);
    });
  } else {
    sections.push('');
    sections.push('No specific files were identified.');
  }
  sections.push('');

  // Detected Errors section
  sections.push('### Detected Errors');
  if (errors.length > 0) {
    sections.push('');
    sections.push('The following errors were detected:');
    sections.push('');
    errors.forEach((error, index) => {
      sections.push(`${index + 1}. ${error}`);
    });
  } else {
    sections.push('');
    sections.push('No specific errors were captured.');
  }
  sections.push('');

  // Suspicious Commits section
  sections.push('### Suspicious Commits');
  if (commits.length > 0) {
    sections.push('');
    sections.push('The following commits may have introduced the regression:');
    sections.push('');
    commits.forEach(commit => {
      const shortSha = commit.sha.substring(0, 7);
      const firstLine = commit.message.split('\n')[0];
      sections.push(`- **${shortSha}** by ${commit.author}: ${firstLine}`);
      if (commit.matchedFiles.length > 0) {
        sections.push(`  - Modified: ${commit.matchedFiles.map(f => `\`${f}\``).join(', ')}`);
      }
    });
  } else {
    sections.push('');
    sections.push('No suspicious commits were identified.');
  }
  sections.push('');

  // Footer
  sections.push('---');
  sections.push('');
  sections.push('**Note:** This is an automated fix attempt. Please review carefully before merging.');
  sections.push('');
  sections.push('*Generated by the workflow failure analysis system.*');

  return sections.join('\n');
}

// Made with Bob
